// ==UserScript==
// @name         P2P Datatables
// @namespace    http://juan.one/helvetas
// @version      2.0
// @description  adds Datatables to P2P Backend.
// @author       http://juan.one/1
// @require      https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.min.js
// @require      https://cdn.datatables.net/v/bs/jq-2.2.4/jszip-2.5.0/pdfmake-0.1.18/dt-1.10.13/b-1.2.4/b-colvis-1.2.4/b-flash-1.2.4/b-html5-1.2.4/b-print-1.2.4/r-2.1.1/se-1.2.0/datatables.min.js
// @resource     datatables_css https://cdn.datatables.net/v/bs/jq-2.2.4/jszip-2.5.0/pdfmake-0.1.18/dt-1.10.13/b-1.2.4/b-colvis-1.2.4/b-flash-1.2.4/b-html5-1.2.4/b-print-1.2.4/r-2.1.1/se-1.2.0/datatables.min.css
// @resource     sort_asc https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.13/images/sort_asc.png
// @resource     sort_asc_disabled https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.13/images/sort_asc_disabled.png
// @resource     sort_both https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.13/images/sort_both.png
// @resource     sort_desc https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.13/images/sort_desc.png
// @resource     sort_desc_disabled https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.13/images/sort_desc_disabled.png
// @match        *://p2p.getunik.net/organisations/helvetas/*
// @match        *://helvetas.raisenow.net/organisations/helvetas/*
// @grant        GM_addStyle
// @grant        GM_getResourceText
// @grant        GM_getResourceURL
// ==/UserScript==
// Generated by CoffeeScript 1.10.0
(function() {
  var add_campaign_details, here, table;

  if (document.location.hostname === "p2p.getunik.net") {
    document.location.hostname = "helvetas.raisenow.net";
  }

  GM_addStyle(GM_getResourceText("datatables_css"));

  GM_addStyle("ul.pagination li { display: inline; margin: 0.3rem; } input[type='text'], textarea, table { width: 100%; } textarea {height: 5em;} table.dataTable thead .sorting_asc:after { content: '▲'; } table.dataTable thead .sorting_asc_disabled:after { content: '△';  } table.dataTable thead .sorting:after { content: '♦︎'; } t.able.dataTable thead .sorting_desc:after { content: '▼'; } table.dataTable thead .sorting_desc_disabled:after { content: '▽'; } .table-striped tbody>tr:nth-child(odd)>td, .table-striped tbody>tr:nth-child(odd)>th { background-color: inherit; } .dt-button { margin-right: 1em; }");

  $.extend($.fn.dataTable.defaults, {
    order: [[0, 'desc']],
    lengthMenu: [[50, -1], [50, "All"]],
    pageLength: 50,
    responsive: true,
    select: true,
    dom: 'Blftipr',
    buttons: [
      {
        extend: 'colvis',
        collectionLayout: 'fixed two-column'
      }, {
        extend: 'copyHtml5',
        text: 'Copy all'
      }, {
        extend: 'copyHtml5',
        text: 'Copy selected',
        exportOptions: {
          modifier: {
            selected: true
          }
        }
      }, {
        extend: 'excelHtml5',
        text: 'XLS all'
      }, {
        extend: 'excelHtml5',
        text: 'XLS selected',
        exportOptions: {
          modifier: {
            selected: true
          }
        }
      }
    ]
  });

  $.fn.extend({
    addDateOrder: function(options) {
      var log, settings;
      settings = {
        formatString: "DD.MM.YYYY HH:mm",
        debug: false
      };
      settings = $.extend(settings, options);
      log = function(message) {
        if (settings.debug) {
          return typeof console !== "undefined" && console !== null ? console.log(message) : void 0;
        }
      };
      return this.each(function() {
        var error, error1, formattedDate;
        try {
          formattedDate = moment($(this)[0].textContent, settings.formatString).format();
          log("formatted date:" + formattedDate);
          return $(this).attr("data-order", formattedDate);
        } catch (error1) {
          error = error1;
          return log("ERROR:\nType: " + error.type + "\nArgs: " + error["arguments"] + "\nMessage: " + error.message);
        }
      });
    }
  });

  $.fn.extend({
    addProperties: function(options) {
      var log, settings;
      settings = {
        campaigns: {},
        debug: false
      };
      settings = $.extend(settings, options);
      log = function(message) {
        if (settings.debug) {
          return typeof console !== "undefined" && console !== null ? console.log(message) : void 0;
        }
      };
      return this.each(function(index) {
        var campaign, campaign_id, campaign_preview, campaign_type, campaigner, campaigner_link, email, is_public, parent_campaign, parent_campaign_id, purpose;
        campaign_id = parseInt($("td:nth-child(1)", this)[0].innerHTML, 10);
        campaign = settings.campaigns[campaign_id];
        log("campaign_id:");
        log(campaign.id);
        campaigner = campaign.user;
        log("campaigner");
        log(JSON.stringify(campaigner));
        email = campaigner.email;
        log("email:");
        log(email);
        purpose = campaign.purpose;
        log("purpose:");
        log(purpose);
        campaign_type = campaign.campaign_type;
        log("campaign_type:");
        log(campaign_type);
        $("td:nth-child(5)", this).append("<a href='mailto:" + email + "'>" + email + "</a>");
        is_public = function(campaign_is_public) {
          if (campaign_is_public) {
            return "public";
          } else {
            return "private";
          }
        };
        $("td:nth-child(10)", this).append(is_public(campaign.is_public));
        $("td:nth-child(12)", this).append("<a href='/organisations/helvetas/purposes/" + (purpose != null ? purpose.identifier : void 0) + "/edit'>" + (purpose != null ? purpose.id : void 0) + ": " + (purpose != null ? purpose.identifier : void 0) + "</a>");
        $("td:nth-child(13)", this).append("<a href='/organisations/helvetas/campaigntypes/" + (campaign_type != null ? campaign_type.identifier : void 0) + "/edit'>" + (campaign_type != null ? campaign_type.id : void 0) + ": " + (campaign_type != null ? campaign_type.identifier : void 0) + "</a>");
        parent_campaign_id = parseInt($("td:nth-child(18)", this)[0].innerHTML, 10);
        if (!isNaN(parent_campaign_id)) {
          log("parent_campaign_id:");
          log(parent_campaign_id);
          parent_campaign = settings.campaigns[parent_campaign_id];
          log("parent_campaign:");
          $("td:nth-child(18)", this)[0].innerHTML = "<a href='/organisations/helvetas/campaigners/" + parent_campaign.user.username + "/campaigns/" + parent_campaign.identifier + "/edit'> " + parent_campaign.id + ": " + parent_campaign.name + " </a>";
        }
        campaigner_link = "<a href='/organisations/helvetas/campaigners/" + campaigner.username + "/edit'> " + campaigner.username + " </a>";
        $("td:nth-child(2)", this)[0].innerHTML = campaigner_link;
        $("td.firstname", this)[0].innerHTML = campaigner.firstname;
        $("td.lastname", this)[0].innerHTML = campaigner.lastname;
        campaign_preview = "| <a href='https://life-changer.helvetas.ch/" + campaigner.username + "/" + campaign.identifier + "'> preview </a>";
        $("td:last-child", this).append(campaign_preview);
        return $("td:nth-child(6)", this)[0].innerText = campaign.identifier;
      });
    }
  });

  add_campaign_details = (function(_this) {
    return function(location) {
      $("<th class='firstname'>First Name</th> <th class='lastname'>Last Name</th> <th class='email'>Email</th>").insertAfter($("th:nth-child(2)"));
      $("<th class='published'>Publication Status</th>").insertAfter($("th:nth-child(9)"));
      $("<th class='purpose'>Purpose</th> <th class='campaign-type'>Type</th>").insertAfter($("th:nth-child(11)"));
      $("tbody tr td:nth-child(2)").after("<td class='firstname'></td> <td class='lastname'></td> <td class='email'></td>");
      $("tbody tr td:nth-child(9)").after("<td class='published'></td>");
      $("tbody tr td:nth-child(11)").after("<td class='purpose'></td> <td class='campaign-type'></td>");
      return $.getJSON(location + ".json", function(data) {
        var campaign, campaigns, i, len, ref, table, tr;
        campaigns = {};
        ref = data.campaigns;
        for (i = 0, len = ref.length; i < len; i++) {
          campaign = ref[i];
          campaigns[campaign.id] = campaign;
        }
        tr = $("tbody tr");
        tr.addProperties({
          campaigns: campaigns
        });
        table = $('table').DataTable();
        $('.span6').addClass('span12').removeClass('span6');
        return table.buttons().container().appendTo($('.col-sm-6:eq(0)', table.table().container()));
      });
    };
  })(this);

  $.fn.extend({
    addCustomTexts: function(options) {
      var log, settings;
      settings = {
        debug: false
      };
      settings = $.extend(settings, options);
      log = function(message) {
        if (settings.debug) {
          return typeof console !== "undefined" && console !== null ? console.log(message) : void 0;
        }
      };
      return this.each(function() {
        var edit_url;
        edit_url = $("> td:nth-child(6) > a:nth-child(1)", this)[0].href;
        log(edit_url);
        $("> td:nth-child(5)", this).after('<td class="custom-text custom-text-en"></td>').after('<td class="custom-text custom-text-it"></td>').after('<td class="custom-text custom-text-fr"></td>').after('<td class="custom-text custom-text-de"></td>');
        $("> td:nth-child(6)", this).load(edit_url + "?locale=de #getunik_p2pentitiesbundle_customtext_text", function(response, status, xhr) {
          if (status === "success") {
            return $(this).append("<a href='" + edit_url + "?locale=de'>edit de</a>");
          }
        });
        $("> td:nth-child(7)", this).load(edit_url + "?locale=fr #getunik_p2pentitiesbundle_customtext_text", function(response, status, xhr) {
          if (status === "success") {
            return $(this).append("<a href='" + edit_url + "?locale=fr'>edit fr</a>");
          }
        });
        $("> td:nth-child(8)", this).load(edit_url + "?locale=it #getunik_p2pentitiesbundle_customtext_text", function(response, status, xhr) {
          if (status === "success") {
            return $(this).append("<a href='" + edit_url + "?locale=it'>edit it</a>");
          }
        });
        return $("> td:nth-child(9)", this).load(edit_url + "?locale=en #getunik_p2pentitiesbundle_customtext_text", function(response, status, xhr) {
          if (status === "success") {
            return $(this).append("<a href='" + edit_url + "?locale=en'>edit en</a>");
          }
        });
      });
    }
  });

  $.fn.extend({
    addCustomTextHeaders: function(options) {
      var log, settings;
      settings = {
        debug: false
      };
      settings = $.extend(settings, options);
      log = function(message) {
        if (settings.debug) {
          return typeof console !== "undefined" && console !== null ? console.log(message) : void 0;
        }
      };
      return this.each(function() {
        return $("> thead > tr > th:nth-child(5)", this).after('<th class="custom-text-head custom-text-head-en">EN</th>').after('<th class="custom-text-head custom-text-head-it">IT</th>').after('<th class="custom-text-head custom-text-head-fr">FR</th>').after('<th class="custom-text-head custom-text-head-de">DE</th>');
      });
    }
  });

  here = window.location.pathname;

  if (here === "/organisations/helvetas/campaign/list") {
    $('.span6').addClass('span12').removeClass('span6');
    $("td:nth-child(0n+4)").addDateOrder({
      formatString: "DD.MM.YYYY"
    });
    $("td:nth-child(0n+5)").addDateOrder({
      formatString: "DD.MM.YYYY"
    });
    add_campaign_details(here);
  } else if (here === "/organisations/helvetas/urlalias/list") {
    $("td:nth-child(0n+3)").addDateOrder({
      formatString: "DD.MM.YYYY HH:mm"
    });
    $("td:nth-child(0n+4)").addDateOrder({
      formatString: "DD.MM.YYYY HH:mm"
    });
    table = $('table').DataTable();
    $('.span6').addClass('span12').removeClass('span6');
    table.buttons().container().appendTo($('.col-sm-6:eq(0)', table.table().container()));
  } else if (here === "/organisations/helvetas/translations/customtexts/list") {
    $("table").addCustomTextHeaders();
    $("table>tbody>tr").addCustomTexts();
    $('.span6').addClass('span12').removeClass('span6');
  } else {
    $('.span6').addClass('span12').removeClass('span6');
    table = $('table').DataTable();
    table.buttons().container().appendTo($('.col-sm-6:eq(0)', table.table().container()));
  }

}).call(this);
